### ISSUE TITLE
App Crashes after user pressing the button to generate new images

### ISSUE THREAD

**Issue by Devlopers** [Devlopers/udacity-virtual-tourist#15]
Reproduced issue App Crashes

not deleted /Users/jchiu/Library/Developer/CoreSimulator/Devices/F402A312-B175-47AC-9FE9-F12BCE0BBB00/data/Containers/Data/Application/21BC01CB-0A82-48CE-919D-AF7DF584CE74/Library/Caches/3219126624_8e93255108.jpg
<img width="1009" alt="screenshot 2016-09-29 13 09 23" src="https://cloud.githubusercontent.com/assets/7025757/18970466/40e931cc-8646-11e6-9e2c-9d9f8fac4f0a.png">

@Jeffchiucp

**Comment by Devlopers** [comment]
more screenshot needed help to fix this bug @Jeffchiucp 
<img width="1274" alt="screenshot 2016-09-29 13 12 43" src="https://cloud.githubusercontent.com/assets/7025757/18970531/7898963a-8646-11e6-8a05-1ff50f130c41.png">

**Comment by Devlopers** [comment]
Simulator screen frozen due to app crash.

NSLog shows that thread 1 is broken at Flickr.swfit
![simulator screen shot sep 29 2016 1 28 29 pm](https://cloud.githubusercontent.com/assets/7025757/18971127/c2df470a-8648-11e6-82e9-105aeefb5262.png)

**Comment by Devlopers** [comment]
successfully reproduced the issue

**Comment by Devlopers** [comment]
@Jeffchiucp  needed update

**Comment by Jeffchiucp** [comment]
resolved issue by enabling the HTTPS connection
